# Generated by Django 5.2.4 on 2025-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_otp_user_otp_exp_user_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
